version: "3"
services:

  uwsgi:
    # ビルドするDockerfileのでディレクトリ相対パス
    build: ./app
    container_name: opop-uwsgi
    # 解放するポートを指定。"ホスト:コンテナ"のマッピング となる
    ports:
      - "3031:3031"
    # コンテナ内の環境変数を指定する
    environment:
      TZ: "Asia/Tokyo"
    networks: 
      - opop

  nginx:
    build: ./nginx
    container_name: opop-nginx
    networks: 
      - opop
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"

networks: 
  opop:
